language: node_js
node_js:
  - 15
services:
  - mongodb
before_install:
  - openssl aes-256-cbc -K  $encrypted_83cbab1bbca1_key -iv $encrypted_83cbab1bbca1_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
install: npm install --save-dev
before_script:
  - sleep 15
  - npm run seed
script:
  - npm test
  - npm run lint:node
  - npm run lint:browser
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - git remote add deploy $CUSTOM_DEPLOY_URL
  - git push deploy HEAD:tprep
